// src/data/initialDetails.js

const initialDetails = [
    {
      id: 1,
      imgPath: "/img/1.png " ,
      name: "Jane Doe",
      email: "janedoe@gmail.com",
      address: "New Delhi, India",
    },
    {
      id: 2,
      imgPath: "/img/2.png",
      name: "Mary Rosamund",
      email: "agra@rosie.com",
      address: "Tbilisi, India",
    },
    {
      id: 3,
      imgPath: "/img/3.png",
      name: "Sherlock Watson",
      email: "irene@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 4,
      imgPath: "/img/4.png",
      name: "John Holmes",
      email: "mary@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 5,
      imgPath: "/img/5.png",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 6,
      imgPath: "/img/1.png",
      name: "Jane Doe",
      email: "janedoe@gmail.com",
      address: "New Delhi, India",
    },
    {
      id: 7,
      imgPath: "/img/2.png",
      name: "Mary Rosamund",
      email: "agra@rosie.com",
      address: "Tbilisi, India",
    },
    {
      id: 8,
      imgPath: "/img/3.png",
      name: "Sherlock Watson",
      email: "irene@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 9,
      imgPath: "/img/4.png",
      name: "John Holmes",
      email: "mary@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 10,
      imgPath: "/img/5.png",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 11,
      imgPath: "/img/1.png",
      name: "Jane Doe",
      email: "janedoe@gmail.com",
      address: "New Delhi, India",
    },
    {
      id: 12,
      imgPath: "/img/2.png",
      name: "Mary Rosamund",
      email: "agra@rosie.com",
      address: "Tbilisi, India",
    },
    {
      id: 13,
      imgPath: "/img/3.png",
      name: "Sherlock Watson",
      email: "irene@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 14,
      imgPath: "/img/4.png",
      name: "John Holmes",
      email: "mary@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 15,
      imgPath: "/img/5.png",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
    {
      id: 16,
      imgPath: "/img/1.png",
      name: "Jane Doe",
      email: "janedoe@gmail.com",
      address: "New Delhi, India",
    },
    {
      id: 17,
      imgPath: "/img/2.png",
      name: "Mary Rosamund",
      email: "agra@rosie.com",
      address: "Tbilisi, India",
    },
    {
      id: 18,
      imgPath: "/img/3.png",
      name: "Sherlock Watson",
      email: "irene@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 19,
      imgPath: "/img/4.png",
      name: "John Holmes",
      email: "mary@johnlock.com",
      address: "Baker Street, India",
    },
    {
      id: 20,
      imgPath: "/img/5.png",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
    },
  ];
  
  export default initialDetails;